### ISSUE TITLE
To-Do List for Serenity Developer Guide

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#31]
Some of tasks in this list are planned, while others are just ideas on what can be done.
- [ ] Movie Tutorial Sample
  - [x] Master/Detail In Memory Editing for Cast
  - [x] Show movies an actor played in as a tab
  - [x] Person / movie main image upload ability
  - [x] Person / movie multiple image upload ability
  - [ ] Front page for viewing movies (/title/123213/lord-of-the-rings)
  - [ ] Front page for viewing persons (/name/5454/keanu-reeves)
- [ ] URL Shortener Sample
  - [ ] Service to register short URLs
  - [ ] List / edit interface for short URLs
  - [ ] API Key / Registration for customers
- [ ] Help Desk / Task Management Sample
  - [ ] Task
  - [ ] Issue (Ticket)
  - [ ] Work Item Linking
  - [ ] Teams
  - [ ] Automatic assignment with priority
  - [ ] Gantt Chart?
  - [ ] Workflow Management and Process Template?
- [ ] Background Task Sample
  - [ ] Bulk Mail Server
- [ ] Configuration Editor Sample
  - [ ] Declaring Settings
  - [ ] Editing Interface for Settings
  - [ ] Handling Different Setting Scopes
- [ ] Dynamic Entities / Fields
  - [ ] Adding Custom Fields To Existing Entities by Enduser
  - [ ] User definable dynamic entity and UI for it (like Dynamics CRM, Sharepoint etc)
- [ ] Reporting Sample
  - [x] Data Only Report
  - [ ] Sql Server Reports
  - [ ] Dynamic Reporting
- [x] Cancellable Bulk Action with Progress Bar Sample
- [ ] Organization Tree / Multi Level Organization Editor Sample
- [ ] Check List Box Sample
- [x] Quick Filter Bar Sample
- [ ] Advanced Filter Editing Sample
- [x] Excel Output Sample
- [x] Script / CSS Bundling
- [ ] Grid Row Ordering Sample
- [x] Formatting in Lookup Editor
- [x] Column Formatters
- [ ] Simple and Advanced Editor Types
- [x] Ajax Actions in Grid (Delete, Perform Operation etc)
- [x] Inline Editing In Grid
- [ ] News Sample
- [ ] Meeting Management Sample and Meeting Request with Outlook etc.
- [ ] Writing Database Tests
- [ ] Content Management System?
- [ ] Forum?
- [x] Temporarily upload a file and parse it (e.g. excel)
- [x] Add extention table editing sample (in tab / dialog / integrated form)

**Comment by ademc** [comment]
Amazing! Which formats will be  suitable: source code, documentation, video tutorial? Are we contribute with some source code?

**Comment by volkanceylan** [comment]
This is my to-do list for developer guide, but i'm open to any contributions. You may send a pull request for code. Write some chapter for Serenity guide in markdown format so i can include it. Video for tutorial in Serenity guide would be cool, as my pronunciation is a bit on poor side :)

**Comment by brettbeard** [comment]
Where is the "Data Only Report" Sample found?

**Comment by volkanceylan** [comment]
Excel output is data only report

**Comment by patilarun69** [comment]
hi volkanceylan,
I am new in Serenity, i download nerp application and facing following issue.

Error	13	The command ""D:\web\NERP-master\NERP\NERP.Web\tools\node\lessc.cmd" "D:\web\NERP-master\NERP\NERP.Web\Content\site\site.less" > "D:\web\NERP-master\NERP\NERP.Web\Content\site\site.css"" exited with code 9009.	D:\web\NERP-master\NERP\NERP.Web\NERP.Web.csproj	1840	5	NERP.Web

Please guide us

Thanks,

**Comment by volkanceylan** [comment]
Please open a new issue with error details in output window. This is todo list.

**Comment by vinaykulkarni89** [comment]
@volkanceylan  can you please share whats status of  Background Task Sample
 Bulk Mail Server, i'm interested to study this

**Comment by dkontod** [comment]
Volcan the checked items on this list are already in the developer guide? e.g where can be found the "Ajax Actions in Grid (Delete, Perform Operation etc)", or "Inline Editing In Grid" or "Excel output"? Should we expect a new version of the developer guide soon? 
By the way, each and every one of the tasks you have listed are amazing. I wish I could help, but I'm a rookie in both, c# and serene, so I can't.

**Comment by thisismymadeupname** [comment]
Are there any plans to bring the documentation up to date?
