### ISSUE TITLE
To-Do List for Serenity

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#32]
- [x] Code generator should produce code compatible with T4 templates (same location, contents)
- [ ] Enum types script (so won't have to run T4, but not sure if it is a good idea yet)
- [ ] ColumnsBundle, FormBundle, TemplateBundle in one combined ServerMetadata?
- [ ] Bundle of Bundles: 
- [x] Optional Typescript support
- [ ] Increase Test Coverage
- [ ] Remove dependency on jQuery UI, or use a custom subset of it. 
- [x] Use Bootstrap where possible
- [x] Switch to flexbox model for form layouts (IE9+?)
- [ ] Look for an alternative to jQuery Validation.
- [ ] Split theme and layout for Serenity widgets, offer a way to exclude default theme
- [x] Give better error message when Row type used with a LookupEditor attribute doesn't have a LookupScipt attribute
- [x] Generate code for multiple rows
- [ ] TimeSpan editor
- [ ] Another kind of captcha
- [x] Add criteria enum overloads
- [x] DateTime2 support
- [x] Expandable categories in form
- [x] Evaluate SlickGrid grouping option
- [x] Evaluate SlickGrid footer & totals option
- [ ] Partial validation summary in toastr message
- [ ] Use Roslyn or DTE for code generation, avoid requirement to build, auto transform if possible
- [ ] Single Page Application model

**Comment by yangyer** [comment]
Can't wait to see the updates.

**Comment by VictorTomaili** [comment]
- Look for an alternative to jQuery Validation
    - [parsleyjs](http://parsleyjs.org)

**Comment by VictorTomaili** [comment]
- Switch to flexbox model for form layouts (IE9+?)
    - [IE 8-9-10 die](http://thenextweb.com/microsoft/2016/01/05/web-developers-rejoice-internet-explorer-8-9-and-10-die-on-tuesday/#gref) (I know end users doesnt leave IE easily but maybe its will be ignored)

**Comment by volkanceylan** [comment]
Nah english requirements not my style :)

**Comment by volkanceylan** [comment]
But +1 for flexbox and bye bye to IE

**Comment by VictorTomaili** [comment]
But still parsley is strong alternative. I cant find better. Maybe we need write new one :smile:

**Comment by uwascan** [comment]
+1 for Single Page Application model. 
Consider Knockoutjs or Vuejs. I already use Serenity with Knockout (not SPA though)
Serenity will eventually dominate the world if this is done

**Comment by samdubey** [comment]
+1 for VueJs
