### ISSUE TITLE
To-Do List for Serene

### ISSUE THREAD

**Issue by volkanceylan** [volkanceylan/Serenity#33]
- [x] Find a way to handle SQL server 2014+ LocalDB errors (edit web.config with powershell?)
- [x] Add some graphics, stats to dashboard
- [ ] Make parts of Serene template as NuGet packages (easier to update)
- [ ] Category / department etc based permissions sample
- [ ] Add inline editing sample for in-memory grid editor
- [ ] Row ordering sample for full table
- [ ] Row ordering sample for groups in table
- [ ] Row ordering sample for in-memory grid editor
